### ISSUE TITLE
求一波纳新时候的逆向题WP

### ISSUE THREAD

**Issue by RandLily** [CNSS/ctfs#5]
对纳新时候的逆向题很感兴趣，尤其是那个Obfuscation，想知道到底是怎么做的，求一波WP，顺便如果可以的话再求一份源码，211146045@qq.com

**Comment by Kyrios0** [comment]
您好，repo中更新了confusion题目的源码，请查看。
如果还有需要请在下面留言即可。

**Comment by RandLily** [comment]
emmm，这个是confusion不是Obfuscation，我记得Obfuscation是20年1月左右的题

**Comment by Kyrios0** [comment]
鄙室不在一月出题的...你要找的是不是杭电VidarTeam？

**Comment by RandLily** [comment]
啊，不好意思。。。不过还是谢谢您提供的题目

**Comment by Kyrios0** [comment]
没事没事，那这个issue我就close了，还有别的问题的话欢迎再新开一个issue。
